name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-book==0.15
  - matplotlib==3.6
  - numpy==1.23
  - pandas==1.5
  - scipy==1.10
  - scikit-learn==1.2
  - pytest==7.1
  - jupyter-sphinx==0.4